BAMBOO_IMAGES= """images/bamboo/1_green_full.jpg
images/bamboo/2_black_full.jpg
images/bamboo/3_black_full.jpg
images/bamboo/4_black_full.jpg
images/bamboo/5_black_full.jpg
images/bamboo/6_white_black_full.jpg
images/bamboo/7_black_full.jpg
images/bamboo/8_black_full.jpg
images/bamboo/9_black_full.jpg
images/bamboo/10_green_full.jpg
images/bamboo/11_black_full.jpg
images/bamboo/12_black_olive_full.jpg
images/bamboo/13_gray_full.jpg
images/bamboo/14_black_full.jpg
images/bamboo/15_green_full.jpg
images/bamboo/16_black_full.jpg
images/bamboo/17_green_white_olive_full.jpg
images/bamboo/18_black_full.jpg
images/bamboo/19_green_full.jpg
images/bamboo/20_gray_full.jpg
images/bamboo/21_silver_full.jpg
images/bamboo/22_white_full.jpg
images/bamboo/23_black_olive_full.jpg
images/bamboo/24_white_full.jpg
images/bamboo/25_black_white_full.jpg
""".strip().splitlines()
MATERIAL_IMAGES = """images/material/black-blue_full.jpg
images/material/black_full.jpg
images/material/black-red_full.jpg
images/material/blue-black_full.jpg
images/material/blue-brown_full.png
images/material/blue_full.jpg
images/material/blue-green_full.png
images/material/blue-lightblue-white_full.jpg
images/material/blue-white_full.jpg
images/material/blue-yellow_full.png
images/material/darkgreen-red-yellow_full.png
images/material/green-blue_full.jpg
images/material/green_full.png
images/material/green-red_full.jpg
images/material/orange-black_full.jpg
images/material/orange-blue_full.jpg
images/material/purple-blue_full.jpg
images/material/purple-blue-red_full.jpg
images/material/purple-red-orange_full.png
images/material/purple-red-white_full.png
images/material/purple-yellow-white_full.png
images/material/red_full.jpg
images/material/red-green_full.jpg
images/material/white-blue_full.png
images/material/yellow-darkgrey-red_full.jpg
""".strip().splitlines()
