# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


<<<<<<< HEAD
=======

>>>>>>> upstream/community
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> upstream/community
=======

>>>>>>> 76fd51af860d509e78465a3f06371c03cd114e1a
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consumption', models.FloatField()),
            ],
        ),
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> upstream/community
=======

>>>>>>> 76fd51af860d509e78465a3f06371c03cd114e1a
        migrations.AddField(
            model_name='calc',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
        migrations.AddField(
            model_name='calc',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device'),
        ),
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> upstream/community
=======

>>>>>>> 76fd51af860d509e78465a3f06371c03cd114e1a
    ]
