# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170531_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.FloatField()),
                ('cost', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='device',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
