# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170601_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='campany',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Campany'),
            preserve_default=False,
        ),
    ]
