# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170601_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('cost', models.FloatField()),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campany')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='campany',
        ),
        migrations.RemoveField(
            model_name='person',
            name='device',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
