# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170601_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='cost',
        ),
    ]
