# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_calc_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='campany',
            new_name='company',
        ),
    ]
