# Generated by Django 3.1.6 on 2021-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_on'], name='blog_commen_created_871382_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='blog_commen_author_c4f747_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_on'], name='blog_post_created_7e46d3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='blog_post_title_e1c6f7_idx'),
        ),
    ]
