# Generated by Django 2.2.2 on 2019-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesseen',
            name='venue_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
