# Generated by Django 2.2.2 on 2019-10-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0008_auto_20191008_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='away_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='away_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='home_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='home_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
