#!python3
#with_ssh is a script to connect to a server and run a command.

import paramiko
from contextlib import contextmanager

server = '127.0.0.1'
username = 'pybites'
password = 'PyBiTeS_DoG'

@contextmanager
def check_hostname(host):
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host, username=username, password=password)
        #ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command('cat /etc/hostname')
        yield ssh
    finally:
        ssh.close()

with check_hostname(server) as ssh:
    ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command('cat /etc/hostname')
    print('%s' % (ssh_stdout.readlines()))
