name: comic_snagger
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.6.0
  - coverage=4.5.1
  - flake8=3.5.0
  - isort=4.3.4
  - mypy=0.630
  - pylint=1.9.2
  - pytest=3.6.2
  - pytest-cov=2.5.1
  - python=3.6.6
  - requests=2.19.1
  - pip:
    - bandit==1.4.0
    - black==18.6b4
