# Generated by Django 2.2.2 on 2019-09-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
