# Generated by Django 2.2.12 on 2020-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200603_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.AddField(
            model_name='challenge',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
