# Generated by Django 2.1.1 on 2018-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
