# Generated by Django 2.1.1 on 2018-09-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_auto_20180930_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='activity',
        ),
    ]
