"""empty message

Revision ID: 79a06767435e
Revises: 
Create Date: 2019-05-10 21:14:24.552697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a06767435e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomo_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('stop', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pomo_task')
    # ### end Alembic commands ###
